# Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - name: grafana-http
      port: 3000
      protocol: TCP
  selector:
    app: grafana
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana1
          image: docker.io/grafana/grafana:9.3.2
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress-route
  namespace: default
spec:
  entryPoints:
    - grafana-http
  routes:
    - kind: Rule
      match: HostRegexp(`{name:.+}`)
      services:
        - name: grafana
          port: 3000
  tls:
    certResolver: default
