#########################################################
## ArangoDB Service, Pod, and Ingress
#########################################################
# Service
apiVersion: v1
kind: Service
metadata:
  name: data-arangodb
spec:
  ports:
    - name: arango-http
      port: 8529
      protocol: TCP
  selector:
    app: data-arangodb
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: data-arangodb
spec:
  containers:
    - name: data-arangodb
      image: docker.io/library/arangodb:3.10.2
      env:
        - name: ARANGO_ROOT_PASSWORD
          value: test123
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumeMounts:
        - mountPath: /var/lib/arangodb3-apps
          name: arangodb-apps-dir
        - mountPath: /var/lib/arangodb3
          name: arangodb-data-dir
  volumes:
    - name: arangodb-apps-dir
      hostPath:
        path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/arangodb/apps
        type: Directory
    - name: arangodb-data-dir
      hostPath:
        path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/arangodb/data
        type: Directory
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: arangodb-ingress-route
  namespace: default
spec:
  entryPoints:
    - arango-http
  routes:
    - kind: Rule
      match: HostRegexp(`.+`)
      services:
        - name: data-arangodb
          port: 8529

---
#########################################################
## MongoDB Service, Pod, and Ingress
#########################################################
# Service
apiVersion: v1
kind: Service
metadata:
  name: data-mongodb
spec:
  ports:
    - name: mongodb-tcp
      port: 27017
      protocol: TCP
  selector:
    app: data-mongodb
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: data-mongodb
spec:
  containers:
    - name: data-mongodb
      image: docker.io/library/mongo:6.0.3
      args:
        - --quiet
        - --bind_ip_all
        - --auth
        - --enableFreeMonitoring
        - "off"
        - --journal
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumeMounts:
        - mountPath: /data/db
          name: mongodb-data-dir
        - mountPath: /data/configdb
          name: mongodb-configdb-dir
  volumes:
    - name: mongodb-data-dir
      hostPath:
        path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/mongodb/db
        type: Directory
    - name: mongodb-configdb-dir
      hostPath:
        path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/mongodb/configdb
        type: Directory
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongodb-ingress-route
  namespace: default
spec:
  entryPoints:
    - mongodb-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: data-mongodb
          port: 27017
  tls:
    passthrough: false

---
#########################################################
## Elasticsearch Service, Pod, and Ingress
#########################################################
# Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch01
spec:
  ports:
    - name: elastic-http
      port: 9200
      protocol: TCP
  selector:
    app: elasticsearch01
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch01
spec:
  containers:
    - name: es01
      image: docker.io/library/elasticsearch:8.5.3
      env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: test123
        - name: xpack.security.enabled
          value: "true"
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data-dir
  volumes:
    - name: elasticsearch-data-dir
      hostPath:
        path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/elasticsearch/data
        type: Directory
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elastic-ingress-route
  namespace: default
spec:
  entryPoints:
    - elastic-http
  routes:
    - kind: Rule
      match: HostRegexp(`.+`)
      services:
        - name: elasticsearch01
          port: 9200

---
#########################################################
## Kibana Service, Pod, and Ingress
#########################################################
# Service
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: kibana-http
      port: 5601
      protocol: TCP
  selector:
    app: kibana
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: kibana
spec:
  containers:
    - name: kibana1
      image: docker.io/library/kibana:8.5.3
      env:
        - name: SERVERNAME
          value: kibana
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch01:9200
        - name: ELASTICSEARCH_USERNAME
          value: kibana_system
        - name: ELASTICSEARCH_PASSWORD
          value: test123
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kibana-ingress-route
  namespace: default
spec:
  entryPoints:
    - kibana-http
  routes:
    - kind: Rule
      match: HostRegexp(`.+`)
      services:
        - name: kibana
          port: 5601

---
#########################################################
## Grafana Service, Pod, and Ingress
#########################################################
# Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - name: grafana-http
      port: 3000
      protocol: TCP
  selector:
    app: grafana
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: grafana
spec:
  containers:
    - name: grafana1
      image: docker.io/grafana/grafana:9.3.2
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress-route
  namespace: default
spec:
  entryPoints:
    - grafana-http
  routes:
    - kind: Rule
      match: HostRegexp(`.+`)
      services:
        - name: grafana
          port: 3000
