# Service
apiVersion: v1
kind: Service
metadata:
  name: data-mongodb
spec:
  ports:
    - name: mongodb-tcp
      port: 27017
      protocol: TCP
  selector:
    app: data-mongodb
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-mongodb
  template:
    metadata:
      labels:
        app: data-mongodb
    spec:
      containers:
        - name: data-mongodb
          image: docker.io/library/mongo:6.0.3
          args:
            - --quiet
            - --bind_ip_all
            - --auth
            - --enableFreeMonitoring
            - "off"
            - --journal
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-dir
            - mountPath: /data/configdb
              name: mongodb-configdb-dir
      volumes:
        - name: mongodb-data-dir
          hostPath:
            path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/mongodb/db
            type: Directory
        - name: mongodb-configdb-dir
          hostPath:
            path: /home/steve/IdeaProjects/podman-caddy-x509/deployment/mongodb/configdb
            type: Directory
---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongodb-ingress-route
  namespace: default
spec:
  entryPoints:
    - mongodb-tcp
  routes:
    - match: HostSNIRegexp(`{name:.+}`)
      services:
        - name: data-mongodb
          port: 27017
  tls:
    passthrough: false
