tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/test.crt
        keyFile: /certs/test.key
  options:
    default:
      minVersion: VersionTLS12
      clientAuth:
        caFiles:
          - /certs/trust.pem
        clientAuthType: RequireAndVerifyClientCert

http:
  middlewares:
    pass-tls-client-cert:
      passTLSClientCert:
        pem: false
        info:
          subject:
            commonName: true
            country: true
            domainComponent: true
            locality: true
            organization: true
            organizationalUnit: true
            province: true
          issuer:
            commonName: true
            country: true
            domainComponent: true
            locality: true
            organization: true
            province: true
